name: jobradar_analytics
version: 1.0.0
config-version: 2
profile: jobradar_analytics
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  jobradar_analytics:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts
      +materialized: table
